name: tests
on: [push, pull_request]
jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: |
          go test ./slice/... -v -count 1

